name: "Add `frontend` label."

on:
  pull_request:
    types: opened
    paths:
      - '**.html'
      - '**.css'
      - '**.js'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: frontend
