name: Auto Merge

on:
  push:
    branchs:
      - frontend

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.PAT_v2 }}  

      - name: Auto merge frontend into develop
        run: |
          git fetch
          git checkout main
          #git config --global user.email "github@action.com"
          #git config --global user.name "GHA"
          git merge --allow-unrelated-histories --no-ff frontend --no-edit
          git push
