name: Change Approval
on:
  pull_request:
    types:
      - labeled

jobs:
  change-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Approval
        run: |
          TOKEN=${{ secrets.FE_reviews_PAT }}
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          LABEL_NAME="frontend"
          MIN_APPROVALS=1

          API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER"
          AUTH_HEADER="Authorization: Bearer $TOKEN"
          ACCEPT_HEADER="Accept: application/vnd.github.v3+json"

          curl -X PATCH -sSL -H "$AUTH_HEADER" -H "$ACCEPT_HEADER" \
            -d "{\"labels\": [\"$LABEL_NAME\"], \"required_pull_request_reviews\": {\"required_approving_review_count\": $MIN_APPROVALS}}" \
            "$API_URL"
